import {
  type CanActivate,
  type ExecutionContext,
  Inject,
  Injectable,
  ServiceUnavailableException,
  UnauthorizedException,
} from '@nestjs/common';
import type { Request } from 'express';
import { timingSafeEqual } from 'node:crypto';
import { APP_CONFIG, type AppConfig } from '../config';

/** Header CloudFront adds to every request it forwards to the API origin. */
export const ORIGIN_VERIFY_HEADER = 'x-origin-verify';

/**
 * Rejects any request that did not come through the CloudFront distribution.
 *
 * CloudFront injects `x-origin-verify` on every request it forwards to the API
 * and overrides any viewer-supplied header of the same name, so a caller can't
 * forge it. A request sent straight to the execute-api URL arrives without it.
 * The value is generated by CDK and never reaches the browser — unlike an API
 * key compiled into the site's JavaScript, which anyone can read.
 *
 * Fails closed: with no secret configured every request is refused.
 */
@Injectable()
export class OriginVerifyGuard implements CanActivate {
  constructor(@Inject(APP_CONFIG) private readonly config: AppConfig) {}

  canActivate(context: ExecutionContext): boolean {
    const request = context.switchToHttp().getRequest<Request>();
    assertFromEdge(request.headers[ORIGIN_VERIFY_HEADER], this.config.originSecret);
    return true;
  }
}

export function assertFromEdge(provided: string | string[] | undefined, expected: string): void {
  if (!expected) {
    throw new ServiceUnavailableException('Service is not configured');
  }
  const value = Array.isArray(provided) ? provided[0] : provided;
  if (!value || !constantTimeEquals(value, expected)) {
    throw new UnauthorizedException();
  }
}

/** timingSafeEqual throws on unequal lengths; the secret's length isn't sensitive. */
function constantTimeEquals(a: string, b: string): boolean {
  const bufA = Buffer.from(a, 'utf8');
  const bufB = Buffer.from(b, 'utf8');
  return bufA.length === bufB.length && timingSafeEqual(bufA, bufB);
}
